---
- name: Panda service
  hosts: all
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: static-panda, tags: static-panda }
    - { role: counting-panda, tags: counting-panda }
