---
- name: copy GET request counter
  copy: src=counting-panda dest=/opt/bigpanda/ owner=root group=root mode=0755

- name: npm install
  npm: path=/opt/bigpanda/counting-panda

- name: setting counting-panda.conf at /etc/init
  copy: src=etc/init/ dest=/etc/init/ owner=root group=root mode=0644

- name: setting counting-panda daemon
  copy: src=etc/init.d/ dest=/etc/init.d/ owner=root group=root mode=0775

- name: starting counting-panda service
  service: name=counting-panda state=started
