---
- name: copy static-panda site files
  copy: src=static-panda dest=/opt/bigpanda/ owner=root group=root mode=0755

- name: npm install
  npm: path=/opt/bigpanda/static-panda

- name: setting static-panda.conf at /etc/init 
  copy: src=etc/init/static-panda.conf dest=/etc/init/ owner=root group=root mode=0644

- name: setting static-panda daemon
  copy: src=etc/init.d/static-panda dest=/etc/init.d/static-panda owner=root group=root mode=0775

- name: running static-panda service
  service: name=static-panda state=started
